apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:4.11-1
    args:
    - $(JENKINS_URL)
    - $(JENKINS_AGENT_SECRET)
    - $(JENKINS_AGENT_NAME)
    env:
    - name: JENKINS_URL
      value: "http://jenkins:8080/"
    - name: JENKINS_AGENT_SECRET
      valueFrom:
        secretKeyRef:
          name: jenkins-agent-secret
          key: agent
    - name: JENKINS_AGENT_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  restartPolicy: Never

